# Generated by Django 3.2.5 on 2022-01-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_date', models.DateTimeField(verbose_name='Date Completed')),
                ('project_summary', models.TextField()),
                ('project_article', models.TextField()),
                ('project_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
